import React from "react";
import { Box, Text } from "ink";
import Spinner from "ink-spinner";
import { color, glyph } from "../theme/theme.js";
import { riskOf } from "../utils/danger.js";
import type { CommandResult } from "../utils/execute.js";
import type { DeltaRow, RepoState } from "../services/repo.js";

export type TurnStatus =
  | "planning"
  | "review"
  | "running"
  | "done"
  | "failed"
  | "cancelled";

export interface Turn {
  id: number;
  request: string;
  commands: string[];
  explanation: string;
  status: TurnStatus;
  results: CommandResult[];
  delta: DeltaRow[];
  /** Set when the request never made it to a plan. */
  error?: string;
  /** Repo snapshots either side of the run, used to derive undo. */
  before?: RepoState;
  after?: RepoState;
  /** Marks a turn that was itself generated by undo, so it is not re-undone. */
  isUndo?: boolean;
  /** Shown under the plan, e.g. an undo that cannot reach the remote. */
  note?: string;
}

interface TurnViewProps {
  turn: Turn;
  width: number;
  /** Index being edited in review, or -1. */
  editIndex?: number;
  /** Rendered in place of the command text while editing. */
  editSlot?: React.ReactNode;
  /** Collapse output lines — used for older turns. */
  compact?: boolean;
}

function CommandLine({
  command,
  result,
  running,
  isLast,
  width,
  compact,
  editing,
  editSlot,
  selected,
}: {
  command: string;
  result?: CommandResult;
  running: boolean;
  isLast: boolean;
  width: number;
  compact: boolean;
  editing: boolean;
  editSlot?: React.ReactNode;
  selected: boolean;
}) {
  const risk = riskOf(command);

  let marker: string = glyph.pending;
  let tone: string = color.rule;
  if (result?.success) {
    marker = glyph.ok;
    tone = color.ok;
  } else if (result && !result.success) {
    marker = glyph.bad;
    tone = color.bad;
  } else if (risk) {
    marker = glyph.warn;
    tone = color.focus;
  }

  const outputLines = compact
    ? []
    : (result?.output ?? "").split("\n").filter(Boolean).slice(0, 4);
  const errorLines = (result?.error ?? "").split("\n").filter(Boolean).slice(0, 4);

  return (
    <Box flexDirection="column">
      <Box>
        <Text color={color.rule}>
          {"  "}
          {isLast ? glyph.branchEnd : glyph.branchMid}{" "}
        </Text>
        {running ? (
          <Text color={color.info}>
            <Spinner type="dots" />
          </Text>
        ) : (
          <Text color={tone} bold={marker !== glyph.pending}>
            {marker}
          </Text>
        )}
        <Text> </Text>
        {editing && editSlot ? (
          editSlot
        ) : (
          <Text
            color={selected ? color.focus : color.text}
            bold={selected}
            wrap="truncate-end"
          >
            {command}
          </Text>
        )}
      </Box>

      {risk && !result && (
        <Box paddingLeft={6}>
          <Text color={color.focus}>{risk}</Text>
        </Box>
      )}

      {outputLines.length > 0 && (
        <Box flexDirection="column" paddingLeft={6}>
          {outputLines.map((line, i) => (
            <Text key={i} color={color.muted} wrap="truncate-end">
              {line}
            </Text>
          ))}
        </Box>
      )}

      {errorLines.length > 0 && (
        <Box flexDirection="column" paddingLeft={6}>
          {errorLines.map((line, i) => (
            <Text key={i} color={color.bad} wrap="truncate-end">
              {line}
            </Text>
          ))}
        </Box>
      )}
    </Box>
  );
}

/**
 * One request and everything it produced. The delta block at the end is the
 * point of the whole tool: it says what changed in the repo, not just what ran.
 */
export default function TurnView({
  turn,
  width,
  editIndex = -1,
  editSlot,
  compact = false,
}: TurnViewProps) {
  const runningIndex =
    turn.status === "running" ? turn.results.length : -1;

  return (
    <Box flexDirection="column" marginBottom={1}>
      <Box>
        <Text color={color.focus} bold>
          {glyph.caret}{" "}
        </Text>
        <Text color={color.text} wrap="truncate-end">
          {turn.request}
        </Text>
      </Box>

      {turn.error && (
        <Box paddingLeft={2}>
          <Text color={color.bad} wrap="wrap">
            {turn.error}
          </Text>
        </Box>
      )}

      {turn.status === "planning" && turn.commands.length === 0 && (
        <Box paddingLeft={2}>
          <Text color={color.info}>
            <Spinner type="dots" />
          </Text>
          <Text color={color.muted}> reading the repo and drafting commands</Text>
        </Box>
      )}

      {turn.explanation && !compact && (
        <Box paddingLeft={2}>
          <Text color={color.muted} wrap="wrap">
            {turn.explanation}
          </Text>
        </Box>
      )}

      {turn.commands.length > 0 && (
        <Box flexDirection="column" marginTop={turn.explanation ? 0 : 0}>
          {turn.commands.map((command, i) => (
            <CommandLine
              key={`${turn.id}-${i}`}
              command={command}
              result={turn.results[i]}
              running={i === runningIndex}
              isLast={i === turn.commands.length - 1}
              width={width}
              compact={compact}
              editing={i === editIndex}
              editSlot={editSlot}
              selected={i === editIndex}
            />
          ))}
        </Box>
      )}

      {turn.status === "planning" && turn.commands.length > 0 && (
        <Box paddingLeft={2}>
          <Text color={color.info}>
            <Spinner type="dots" />
          </Text>
          <Text color={color.rule}> still writing the plan</Text>
        </Box>
      )}

      {turn.note && (
        <Box paddingLeft={2}>
          <Text color={color.focus} wrap="wrap">
            {glyph.warn} {turn.note}
          </Text>
        </Box>
      )}

      {turn.status === "cancelled" && (
        <Box paddingLeft={2}>
          <Text color={color.muted}>Cancelled. Nothing ran.</Text>
        </Box>
      )}

      {turn.delta.length > 0 && (
        <Box flexDirection="column" marginTop={1} paddingLeft={2}>
          <Text color={color.brandDim} bold>
            CHANGED
          </Text>
          {turn.delta.map((row) => (
            <Box key={row.key}>
              <Box width={11}>
                <Text color={color.muted}> {row.label}</Text>
              </Box>
              <Text color={color.muted}>{row.from}</Text>
              <Text color={color.rule}>{` ${glyph.arrow} `}</Text>
              <Text color={color.focus} bold>
                {row.to}
              </Text>
            </Box>
          ))}
        </Box>
      )}
    </Box>
  );
}
